[project]
name = "pion-examples"
version = "0.1.0"
description = "Pion examples scripts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pion",
]

[tool.uv.sources]
pion = { git = "https://github.com/OnisOris/pion" }
